data <- read.table("household_power_consumption.txt",header = TRUE, sep =";",na.strings = "?")
data <- subset(data,as.Date(data$Date, "%d/%m/%Y") >= as.Date("2007-2-1") & as.Date(data$Date, "%d/%m/%Y") <= as.Date("2007-2-2"))
dateandtime <- strptime(paste(data$Date,data$Time,sep=" "), "%d/%m/%Y %H:%M:%S")
data <- cbind(dateandtime,data)
plot(data$Global_active_power~data$dateandtime,type="l", ylab="Global Active Power (kilowatts)",xlab="")
dev.copy(png,"plot2.png", width=480, height=480)
dev.off()